### ISSUE TITLE
Ironman2 Color Scheme?

### ISSUE THREAD

**Issue by ricomonster** [sri-ni/ironman-color-scheme#1]
how will i activate it? is it included in the theme? because i can just see the ironman1 color scheme.

**Comment by sri-ni** [comment]
So, sorry Rico. Please check now. I've added the color scheme. Major miss! I hope you enjoy it.

**Comment by sri-ni** [comment]
Definitely fixed. Closing the issue.

**Comment by ricomonster** [comment]
thank you!
